# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AudioflowApi < Formula
  desc "AudioFlow backend API — STT cascade + WS streaming"
  homepage "https://gitlab.com/andrebassi/audioflow"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://gitlab.com/andrebassi/audioflow/-/releases/v0.4.0/downloads/audioflow-api_0.4.0_Darwin_x86_64.tar.gz"
      sha256 "512bc3f54434fe9fea5ace6ddbd860d9aeb4b9211a8e743eb3351d866637dfd5"

      define_method(:install) do
        bin.install "audioflow-api"
      end
    end
    if Hardware::CPU.arm?
      url "https://gitlab.com/andrebassi/audioflow/-/releases/v0.4.0/downloads/audioflow-api_0.4.0_Darwin_arm64.tar.gz"
      sha256 "f72b10dc9a5a696f19cfe7f247584900895af90cef32e23a488cd45b1860100c"

      define_method(:install) do
        bin.install "audioflow-api"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://gitlab.com/andrebassi/audioflow/-/releases/v0.4.0/downloads/audioflow-api_0.4.0_Linux_x86_64.tar.gz"
      sha256 "855806a54f74e966de7c0a3f416f150d26922c5055377b6f4c2f0a88edda2413"
      define_method(:install) do
        bin.install "audioflow-api"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://gitlab.com/andrebassi/audioflow/-/releases/v0.4.0/downloads/audioflow-api_0.4.0_Linux_arm64.tar.gz"
      sha256 "0108ceb155c2f210d3792455702dd9142d7a0c90dca6996a598cfb51bd168af5"
      define_method(:install) do
        bin.install "audioflow-api"
      end
    end
  end

  test do
    assert_match "ok", shell_output("#{bin}/audioflow-api --health || true")
  end
end
