# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Audioflow < Formula
  desc "AudioFlow backend API — STT cascade + WS streaming"
  homepage "https://gitlab.com/andrebassi/audioflow"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://gitlab.com/andrebassi/audioflow/-/releases/v0.4.1/downloads/audioflow_0.4.1_Darwin_x86_64.tar.gz"
      sha256 "220ac17c23a0446d49fc0921bfd2501c0200db6b1f75f0701a9f8bcfb3bacb4c"

      define_method(:install) do
        bin.install "audioflow"
      end
    end
    if Hardware::CPU.arm?
      url "https://gitlab.com/andrebassi/audioflow/-/releases/v0.4.1/downloads/audioflow_0.4.1_Darwin_arm64.tar.gz"
      sha256 "e76bf7e499dcb12add726b841c7c7ae9209918db7df2ea994268c13aa829209e"

      define_method(:install) do
        bin.install "audioflow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://gitlab.com/andrebassi/audioflow/-/releases/v0.4.1/downloads/audioflow_0.4.1_Linux_x86_64.tar.gz"
      sha256 "f3f3e62136405f24a4d6b125ae650e4f95411511ba7d9b24aeafbb51deeedb19"
      define_method(:install) do
        bin.install "audioflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://gitlab.com/andrebassi/audioflow/-/releases/v0.4.1/downloads/audioflow_0.4.1_Linux_arm64.tar.gz"
      sha256 "56e7df94135ddc6740d2858aeffffb8fb608b2943f7fd6fc313c69b91ce1e5d2"
      define_method(:install) do
        bin.install "audioflow"
      end
    end
  end

  test do
    assert_match "ok", shell_output("#{bin}/audioflow --health || true")
  end
end
